language: csharp
solution: Selenium.WebDriver.Extensions.sln
install:
  - nuget restore Selenium.WebDriver.Extensions.sln
  - export SHFBROOT=$TRAVIS_BUILD_DIR/packages/SHFB.2014.5.31/tools/Sandcastle\ Help\ File\ Builder
script:
  - xbuild /p:Configuration=Mono ./Selenium.WebDriver.Extensions.sln
