branches:
  only:
    - master
    - develop
    - /feature.*/
    - /bugfix.*/
    - /release.*/      

skip_tags: true
skip_branch_with_pr: true
skip_commits:
  message: /\[(skip ci|ci skip)\]/

version: 3.2.1.{build}
image: Visual Studio 2017
  
install:
  - choco install msbuild-sonarqube-runner -y
  - choco install googlechrome -y --ignore-checksums
  - choco install opencover.portable -y
  - choco install codecov -y

nuget:
  disable_publish_on_pr: true

environment:
  SonarQubeAccessToken:
    secure: hZ+EdDQLy/K+ngEIPrw7DM//Lft9RldmiOoGNhNz8m9iyfJ3ZJhylBm0FduR6fWT
  GitHubAccessToken:
    secure: r+IxpBcxWvxwGdiNvsHFEWa0wa8WPzw3uRi+1/ObwPoGS16bzG9FObtJIsFdmj0L
      
build_script:
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { SonarScanner.MSBuild.exe begin /n:Selenium.WebDriver.Extensions /k:selenium.webdriver.extensions /v:3.0 /d:sonar.host.url=https://sonarqube.com /d:sonar.organization=rayell-github /d:sonar.login=$env:SonarQubeAccessToken /d:sonar.analysis.mode=preview /d:sonar.github.pullRequest=$env:APPVEYOR_PULL_REQUEST_NUMBER /d:sonar.github.repository=Softlr/Selenium.WebDriver.Extensions /d:sonar.github.oauth=$env:GitHubAccessToken /d:sonar.cs.opencover.reportsPaths=coverage.xml }
  - ps: if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { SonarScanner.MSBuild.exe begin /n:Selenium.WebDriver.Extensions /k:selenium.webdriver.extensions /v:3.0 /d:sonar.host.url=https://sonarqube.com /d:"sonar.organization=rayell-github" /d:"sonar.login=$env:SonarQubeAccessToken" /d:"sonar.cs.opencover.reportsPaths=coverage.xml" }
  - dotnet build -c Release

after_build:
  - dotnet pack -c Release --include-symbols --include-source --no-build -o %APPVEYOR_BUILD_FOLDER% /p:Version=3.2.1

test_script:
  - ps: >-
      & $env:xunit20\xunit.console test\Selenium.WebDriver.Extensions.Tests\bin\Release\net472\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all -appveyor
  - ps: >-
      & $env:xunit20\xunit.console.exe test\Selenium.WebDriver.Extensions.IntegrationTests\bin\Release\net472\Selenium.WebDriver.Extensions.IntegrationTests.dll -noshadow -parallel all -appveyor -trait Browser=Chrome
  - ps: >-
      & $env:xunit20\xunit.console.exe test\Selenium.WebDriver.Extensions.IntegrationTests\bin\Release\net472\Selenium.WebDriver.Extensions.IntegrationTests.dll -noshadow -parallel all -appveyor -trait Browser=InternetExplorer
  - ps: OpenCover.Console.exe -register:user -target:$env:xunit20\xunit.console.exe -targetargs:"test\Selenium.WebDriver.Extensions.Tests\bin\Release\net472\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all" -output:coverage.xml -filter:"+[Selenium.WebDriver.Extensions*]* -[*]*Exception* -[*Tests]* -[xunit*]*"
  - ps: SonarScanner.MSBuild.exe end /d:sonar.login=$env:SonarQubeAccessToken

after_test:
  - codecov -f coverage.xml

artifacts:
  - path: coverage.xml
  - path: .\*.nupkg

deploy:
  - provider: NuGet
    on:
      branch: master
    api_key:
      secure: kvwvA4clT64FDfanLoNcTLWpQlMGQ311zUfwAEljDwHhjtmFCy4O+gSZ2YrGTUYb
  - provider: GitHub
    on:
      branch: master
    release: 3.2.1
    artifact: /.*\.nupkg/
    auth_token:
      secure: r+IxpBcxWvxwGdiNvsHFEWa0wa8WPzw3uRi+1/ObwPoGS16bzG9FObtJIsFdmj0L
