# master branch configuration
-
  branches:
    only:
      - master

  skip_tags: true
  skip_commits:
    message: /Update.*\.md/

  version: 3.1.0.{build}
  configuration: Release
  image: Visual Studio 2017
  
  install:
    - choco install "msbuild-sonarqube-runner" -y

  nuget:
    disable_publish_on_pr: true

  environment:
    GH_ACCESS_TOKEN:
      secure: r+IxpBcxWvxwGdiNvsHFEWa0wa8WPzw3uRi+1/ObwPoGS16bzG9FObtJIsFdmj0L
    SonarQubeAccessToken:
      secure: hZ+EdDQLy/K+ngEIPrw7DM//Lft9RldmiOoGNhNz8m9iyfJ3ZJhylBm0FduR6fWT
    GitHubAccessToken:
      secure: r+IxpBcxWvxwGdiNvsHFEWa0wa8WPzw3uRi+1/ObwPoGS16bzG9FObtJIsFdmj0L
      
  before_build:
    - nuget restore

  build_script:
    - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { MSBuild.SonarQube.Runner.exe begin /n:Selenium.WebDriver.Extensions /k:selenium.webdriver.extensions /v:3.0 /d:sonar.host.url=https://sonarqube.com /d:sonar.organization=rayell-github /d:sonar.login=$env:SonarQubeAccessToken /d:sonar.analysis.mode=preview /d:sonar.github.pullRequest=$env:APPVEYOR_PULL_REQUEST_NUMBER /d:sonar.github.repository=Softlr/Selenium.WebDriver.Extensions /d:sonar.github.oauth=$env:GitHubAccessToken /d:sonar.cs.opencover.reportsPaths=coverage.xml }
    - ps: if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { MSBuild.SonarQube.Runner.exe begin /n:Selenium.WebDriver.Extensions /k:selenium.webdriver.extensions /v:3.0 /d:sonar.host.url=https://sonarqube.com /d:"sonar.organization=rayell-github" /d:"sonar.login=$env:SonarQubeAccessToken" /d:"sonar.cs.opencover.reportsPaths=coverage.xml" }
    - msbuild Selenium.WebDriver.Extensions.sln /t:Rebuild

  after_build:
    - nuget pack src\Selenium.WebDriver.Extensions\Selenium.WebDriver.Extensions.nuspec -Version 3.1.0 -Symbols

  test_script:
  - ps: >-
      & (Resolve-Path $env:USERPROFILE\.nuget\packages\xunit.runner.console\*\tools\net452\xunit.console.exe) test\Selenium.WebDriver.Extensions.Tests\bin\$env:Configuration\net46\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all -appveyor
  - ps: >-
      & (Resolve-Path $env:USERPROFILE\.nuget\packages\xunit.runner.console\*\tools\net452\xunit.console.exe) test\Selenium.WebDriver.Extensions.IntegrationTests\bin\$env:Configuration\net46\Selenium.WebDriver.Extensions.IntegrationTests.dll -noshadow -parallel all -appveyor -trait Browser=PhantomJS
  after_test:
  - ps: >-
      & (Resolve-Path $env:USERPROFILE\.nuget\packages\JetBrains.ReSharper.CommandLineTools\*\tools\inspectcode.exe) Selenium.WebDriver.Extensions.sln --output=ReSharper.xml /no-swea
  - ps: >-
      & (Resolve-Path $env:USERPROFILE\.nuget\packages\OpenCover\*\tools\OpenCover.Console.exe) -register:user -target:(Resolve-Path $env:USERPROFILE\.nuget\packages\xunit.runner.console\*\tools\net452\xunit.console.exe) -targetargs:"test\Selenium.WebDriver.Extensions.Tests\bin\$env:Configuration\net46\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all" -output:coverage.xml -filter:"+[Selenium.WebDriver.Extensions*]* -[*]*Exception* -[*Tests]* -[xunit*]*"
  - ps: >-
      & (Resolve-Path $env:USERPROFILE\.nuget\packages\ReportGenerator\*\tools\ReportGenerator.exe) -reports:coverage.xml -targetdir:CoverageReport
  - SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%"
  - pip install codecov
  - codecov -f coverage.xml
  - ps: MSBuild.SonarQube.Runner.exe end /d:sonar.login=$env:SonarQubeAccessToken

  artifacts:
    - path: ReSharper.xml
    - path: coverage.xml
    - path: CoverageReport
    - path: .\*.nupkg

  deploy:
    - provider: NuGet
      api_key:
        secure: kvwvA4clT64FDfanLoNcTLWpQlMGQ311zUfwAEljDwHhjtmFCy4O+gSZ2YrGTUYb
    - provider: GitHub
      release: 3.1.0
      artifact: /.*\.nupkg/
      auth_token:
        secure: r+IxpBcxWvxwGdiNvsHFEWa0wa8WPzw3uRi+1/ObwPoGS16bzG9FObtJIsFdmj0L

# develop, feature & bugfix branches
-
  branches:
    only:
      - develop
      - /feature.*/
      - /bugfix.*/

  skip_tags: true
  skip_commits:
    message: /Update.*\.md/

  version: 3.1.0.{build}
  configuration: Release
  image: Visual Studio 2017
  
  install:
    - choco install "msbuild-sonarqube-runner" -y
  
  nuget:
    disable_publish_on_pr: true
    
  environment:
    SonarQubeAccessToken:
      secure: hZ+EdDQLy/K+ngEIPrw7DM//Lft9RldmiOoGNhNz8m9iyfJ3ZJhylBm0FduR6fWT
    GitHubAccessToken:
      secure: r+IxpBcxWvxwGdiNvsHFEWa0wa8WPzw3uRi+1/ObwPoGS16bzG9FObtJIsFdmj0L
    
  before_build:
    - nuget restore

  build_script:
    - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { MSBuild.SonarQube.Runner.exe begin /n:Selenium.WebDriver.Extensions /k:selenium.webdriver.extensions /v:3.0 /d:sonar.host.url=https://sonarqube.com /d:sonar.organization=rayell-github /d:sonar.login=$env:SonarQubeAccessToken /d:sonar.analysis.mode=preview /d:sonar.github.pullRequest=$env:APPVEYOR_PULL_REQUEST_NUMBER /d:sonar.github.repository=Softlr/Selenium.WebDriver.Extensions /d:sonar.github.oauth=$env:GitHubAccessToken /d:sonar.cs.opencover.reportsPaths=coverage.xml }
    - ps: if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { MSBuild.SonarQube.Runner.exe begin /n:Selenium.WebDriver.Extensions /k:selenium.webdriver.extensions /v:3.0 /d:sonar.host.url=https://sonarqube.com /d:"sonar.organization=rayell-github" /d:"sonar.login=$env:SonarQubeAccessToken" /d:"sonar.cs.opencover.reportsPaths=coverage.xml" }
    - msbuild Selenium.WebDriver.Extensions.sln /t:Rebuild

  after_build:
    - nuget pack src\Selenium.WebDriver.Extensions\Selenium.WebDriver.Extensions.nuspec -Version 3.1.0-dev -Symbols

  test_script:
  - ps: >-
      & (Resolve-Path $env:USERPROFILE\.nuget\packages\xunit.runner.console\*\tools\net452\xunit.console.exe) test\Selenium.WebDriver.Extensions.Tests\bin\$env:Configuration\net46\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all -appveyor
  - ps: >-
      & (Resolve-Path $env:USERPROFILE\.nuget\packages\xunit.runner.console\*\tools\net452\xunit.console.exe) test\Selenium.WebDriver.Extensions.IntegrationTests\bin\$env:Configuration\net46\Selenium.WebDriver.Extensions.IntegrationTests.dll -noshadow -parallel all -appveyor -trait Browser=PhantomJS
  after_test:
  - ps: >-
      & (Resolve-Path $env:USERPROFILE\.nuget\packages\JetBrains.ReSharper.CommandLineTools\*\tools\inspectcode.exe) Selenium.WebDriver.Extensions.sln --output=ReSharper.xml /no-swea
  - ps: >-
      & (Resolve-Path $env:USERPROFILE\.nuget\packages\OpenCover\*\tools\OpenCover.Console.exe) -register:user -target:(Resolve-Path $env:USERPROFILE\.nuget\packages\xunit.runner.console\*\tools\net452\xunit.console.exe) -targetargs:"test\Selenium.WebDriver.Extensions.Tests\bin\$env:Configuration\net46\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all" -output:coverage.xml -filter:"+[Selenium.WebDriver.Extensions*]* -[*]*Exception* -[*Tests]* -[xunit*]*"
  - ps: >-
      & (Resolve-Path $env:USERPROFILE\.nuget\packages\ReportGenerator\*\tools\ReportGenerator.exe) -reports:coverage.xml -targetdir:CoverageReport
  - SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%"
  - pip install codecov
  - codecov -f coverage.xml
  - ps: MSBuild.SonarQube.Runner.exe end /d:sonar.login=$env:SonarQubeAccessToken

  artifacts:
    - path: ReSharper.xml
    - path: coverage.xml
    - path: CoverageReport
    - path: .\*.nupkg

# release branch configuration
-
  branches:
    only:
      - /release.*/

  skip_tags: true
  skip_commits:
    message: /Update.*\.md/

  version: 3.1.0.{build}
  configuration: Release
  image: Visual Studio 2017
  
  install:
    - choco install "msbuild-sonarqube-runner" -y

  nuget:
    disable_publish_on_pr: true
    
  environment:
    SonarQubeAccessToken:
      secure: hZ+EdDQLy/K+ngEIPrw7DM//Lft9RldmiOoGNhNz8m9iyfJ3ZJhylBm0FduR6fWT
    GitHubAccessToken:
      secure: r+IxpBcxWvxwGdiNvsHFEWa0wa8WPzw3uRi+1/ObwPoGS16bzG9FObtJIsFdmj0L
  
  before_build:
  - nuget restore

  build_script:
    - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { MSBuild.SonarQube.Runner.exe begin /n:Selenium.WebDriver.Extensions /k:selenium.webdriver.extensions /v:3.0 /d:sonar.host.url=https://sonarqube.com /d:sonar.organization=rayell-github /d:sonar.login=$env:SonarQubeAccessToken /d:sonar.analysis.mode=preview /d:sonar.github.pullRequest=$env:APPVEYOR_PULL_REQUEST_NUMBER /d:sonar.github.repository=Softlr/Selenium.WebDriver.Extensions /d:sonar.github.oauth=$env:GitHubAccessToken /d:sonar.cs.opencover.reportsPaths=coverage.xml }
    - ps: if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { MSBuild.SonarQube.Runner.exe begin /n:Selenium.WebDriver.Extensions /k:selenium.webdriver.extensions /v:3.0 /d:sonar.host.url=https://sonarqube.com /d:"sonar.organization=rayell-github" /d:"sonar.login=$env:SonarQubeAccessToken" /d:"sonar.cs.opencover.reportsPaths=coverage.xml" }
    - msbuild Selenium.WebDriver.Extensions.sln /t:Rebuild

  after_build:
    - nuget pack src\Selenium.WebDriver.Extensions\Selenium.WebDriver.Extensions.nuspec -Version 3.1.0-rc -Symbols

  test_script:
  - ps: >-
      & (Resolve-Path $env:USERPROFILE\.nuget\packages\xunit.runner.console\*\tools\net452\xunit.console.exe) test\Selenium.WebDriver.Extensions.Tests\bin\$env:Configuration\net46\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all -appveyor
  - ps: >-
      & (Resolve-Path $env:USERPROFILE\.nuget\packages\xunit.runner.console\*\tools\net452\xunit.console.exe) test\Selenium.WebDriver.Extensions.IntegrationTests\bin\$env:Configuration\net46\Selenium.WebDriver.Extensions.IntegrationTests.dll -noshadow -parallel all -appveyor -trait Browser=PhantomJS
  after_test:
  - ps: >-
      & (Resolve-Path $env:USERPROFILE\.nuget\packages\JetBrains.ReSharper.CommandLineTools\*\tools\inspectcode.exe) Selenium.WebDriver.Extensions.sln --output=ReSharper.xml /no-swea
  - ps: >-
      & (Resolve-Path $env:USERPROFILE\.nuget\packages\OpenCover\*\tools\OpenCover.Console.exe) -register:user -target:(Resolve-Path $env:USERPROFILE\.nuget\packages\xunit.runner.console\*\tools\net452\xunit.console.exe) -targetargs:"test\Selenium.WebDriver.Extensions.Tests\bin\$env:Configuration\net46\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all" -output:coverage.xml -filter:"+[Selenium.WebDriver.Extensions*]* -[*]*Exception* -[*Tests]* -[xunit*]*"
  - ps: >-
      & (Resolve-Path $env:USERPROFILE\.nuget\packages\ReportGenerator\*\tools\ReportGenerator.exe) -reports:coverage.xml -targetdir:CoverageReport
  - SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%"
  - pip install codecov
  - codecov -f coverage.xml
  - ps: MSBuild.SonarQube.Runner.exe end /d:sonar.login=$env:SonarQubeAccessToken

  artifacts:
    - path: ReSharper.xml
    - path: coverage.xml
    - path: CoverageReport
    - path: .\*.nupkg

  deploy:
    - provider: GitHub
      release: 3.1.0-rc
      artifact: /.*\.nupkg/
      auth_token:
        secure: r+IxpBcxWvxwGdiNvsHFEWa0wa8WPzw3uRi+1/ObwPoGS16bzG9FObtJIsFdmj0L
      prerelease: true
