build:
  project: Selenium.WebDriver.Extensions.sln
before_build:
  - nuget install .nuget/packages.config -o packages
  - nuget restore Selenium.WebDriver.Extensions.sln
  - xcopy /Y .nuget\NAnt.exe.config packages\NAnt.Portable.0.92\
test:
  assemblies:
    - Selenium.WebDriver.Extensions.Tests.dll
    - Selenium.WebDriver.Extensions.JQuery.Tests.dll
    - Selenium.WebDriver.Extensions.Sizzle.Tests.dll
    - Selenium.WebDriver.Extensions.QuerySelector.Tests.dll