build:
  project: src/SeleniumHelpers.sln
before_build:
  - nuget install src/.nuget/packages.config -o src/packages
  - nuget restore src/SeleniumHelpers.sln
  - xcopy /Y src\.nuget\NAnt.exe.config src\packages\NAnt.Portable.0.92\