# master branch configuration
-
  branches:
    only:
      - master

  skip_tags: true
  skip_commits:
    message: /Update.*\.md/

  version: 3.0.1.{build}
  configuration: Release
  os: Visual Studio 2015
  
  cache:
    - packages -> **\packages.config

  install:
    - SET PATH=%APPVEYOR_BUILD_FOLDER%\packages\PhantomJS.2.1.1\tools\phantomjs;%PATH%

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "3.0.1"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true

  environment:
    GH_ACCESS_TOKEN:
      secure: r+IxpBcxWvxwGdiNvsHFEWa0wa8WPzw3uRi+1/ObwPoGS16bzG9FObtJIsFdmj0L
      
  before_build:
    - nuget restore

  build:
    project: Selenium.WebDriver.Extensions.sln

  after_build:
    - msbuild Selenium.WebDriver.Extensions.sln /property:Configuration=Docs /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - nuget pack src\Selenium.WebDriver.Extensions\Selenium.WebDriver.Extensions.nuspec -Version 3.0.1 -Symbols

  test_script:
    - packages\xunit.runner.console.2.1.0\tools\xunit.console.exe test\Selenium.WebDriver.Extensions.Tests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all -appveyor
    - packages\xunit.runner.console.2.1.0\tools\xunit.console.exe test\Selenium.WebDriver.Extensions.IntegrationTests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.IntegrationTests.dll -noshadow -parallel all -appveyor -trait Browser=PhantomJS

  after_test:
    - packages\JetBrains.ReSharper.CommandLineTools.2016.2.20160913.100041\tools\inspectcode.exe Selenium.WebDriver.Extensions.sln --output=ReSharper.xml /no-swea
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:"test\Selenium.WebDriver.Extensions.Tests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all" -output:coverage.xml -filter:"+[Selenium.WebDriver.Extensions*]* -[*]*Exception* -[*Tests]* -[xunit*]*"
    - packages\ReportGenerator.2.5.1\tools\ReportGenerator.exe -reports:coverage.xml -targetdir:CoverageReport
    - SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%"
    - pip install codecov
    - codecov -f coverage.xml

  artifacts:
    - path: ReSharper.xml
    - path: coverage.xml
    - path: docs\bin\Docs
    - path: CoverageReport
    - path: .\*.nupkg

  deploy:
    - provider: NuGet
      api_key:
        secure: kvwvA4clT64FDfanLoNcTLWpQlMGQ311zUfwAEljDwHhjtmFCy4O+gSZ2YrGTUYb
    - provider: GitHub
      release: 3.0.1
      artifact: /.*\.nupkg/
      auth_token:
        secure: r+IxpBcxWvxwGdiNvsHFEWa0wa8WPzw3uRi+1/ObwPoGS16bzG9FObtJIsFdmj0L

# develop, feature & bugfix branches
-
  branches:
    only:
      - develop
      - /feature.*/
      - /bugfix.*/

  skip_tags: true
  skip_commits:
    message: /Update.*\.md/

  version: 3.0.2.{build}
  configuration: Release
  os: Visual Studio 2015
  
  cache:
    - packages -> **\packages.config

  install:
    - SET PATH=%APPVEYOR_BUILD_FOLDER%\packages\PhantomJS.2.1.1\tools\phantomjs;%PATH%

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "3.0.2"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}-dev"

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true
    
  before_build:
    - nuget restore

  build:
    project: Selenium.WebDriver.Extensions.sln

  after_build:
    - msbuild Selenium.WebDriver.Extensions.sln /property:Configuration=Docs /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - nuget pack src\Selenium.WebDriver.Extensions\Selenium.WebDriver.Extensions.nuspec -Version 3.0.2-dev -Symbols

  test_script:
    - packages\xunit.runner.console.2.1.0\tools\xunit.console.exe test\Selenium.WebDriver.Extensions.Tests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all -appveyor
    - packages\xunit.runner.console.2.1.0\tools\xunit.console.exe test\Selenium.WebDriver.Extensions.IntegrationTests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.IntegrationTests.dll -noshadow -parallel all -appveyor -trait Browser=PhantomJS

  after_test:
    - packages\JetBrains.ReSharper.CommandLineTools.2016.2.20160913.100041\tools\inspectcode.exe Selenium.WebDriver.Extensions.sln --output=ReSharper.xml /no-swea
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:"test\Selenium.WebDriver.Extensions.Tests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all" -output:coverage.xml -filter:"+[Selenium.WebDriver.Extensions*]* -[*]*Exception* -[*Tests]* -[xunit*]*"
    - packages\ReportGenerator.2.5.1\tools\ReportGenerator.exe -reports:coverage.xml -targetdir:CoverageReport
    - SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%"
    - pip install codecov
    - codecov -f coverage.xml

  artifacts:
    - path: ReSharper.xml
    - path: coverage.xml
    - path: docs\bin\Docs
    - path: CoverageReport
    - path: .\*.nupkg

# release branch configuration
-
  branches:
    only:
      - /release.*/

  skip_tags: true
  skip_commits:
    message: /Update.*\.md/

  version: 3.0.2.{build}
  configuration: Release
  os: Visual Studio 2015
  
  cache:
    - packages -> **\packages.config

  install:
    - SET PATH=%APPVEYOR_BUILD_FOLDER%\packages\PhantomJS.2.1.1\tools\phantomjs;%PATH%

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "3.0.2"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}-rc"

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true
  
  before_build:
  - nuget restore

  build:
    project: Selenium.WebDriver.Extensions.sln

  after_build:
    - msbuild Selenium.WebDriver.Extensions.sln /property:Configuration=Docs /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - nuget pack src\Selenium.WebDriver.Extensions\Selenium.WebDriver.Extensions.nuspec -Version 3.0.2-rc -Symbols

  test_script:
    - packages\xunit.runner.console.2.1.0\tools\xunit.console.exe test\Selenium.WebDriver.Extensions.Tests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all -appveyor
    - packages\xunit.runner.console.2.1.0\tools\xunit.console.exe test\Selenium.WebDriver.Extensions.IntegrationTests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.IntegrationTests.dll -noshadow -parallel all -appveyor -trait Browser=PhantomJS

  after_test:
    - packages\JetBrains.ReSharper.CommandLineTools.2016.2.20160913.100041\tools\inspectcode.exe Selenium.WebDriver.Extensions.sln --output=ReSharper.xml /no-swea
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:"test\Selenium.WebDriver.Extensions.Tests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all" -output:coverage.xml -filter:"+[Selenium.WebDriver.Extensions*]* -[*]*Exception* -[*Tests]* -[xunit*]*"
    - packages\ReportGenerator.2.5.1\tools\ReportGenerator.exe -reports:coverage.xml -targetdir:CoverageReport
    - SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%"
    - pip install codecov
    - codecov -f coverage.xml

  artifacts:
    - path: ReSharper.xml
    - path: coverage.xml
    - path: docs\bin\Docs
    - path: CoverageReport
    - path: .\*.nupkg

  deploy:
    - provider: NuGet
      api_key:
        secure: kvwvA4clT64FDfanLoNcTLWpQlMGQ311zUfwAEljDwHhjtmFCy4O+gSZ2YrGTUYb
    - provider: GitHub
      release: 3.0.2-rc
      artifact: /.*\.nupkg/
      auth_token:
        secure: r+IxpBcxWvxwGdiNvsHFEWa0wa8WPzw3uRi+1/ObwPoGS16bzG9FObtJIsFdmj0L
      prerelease: true
