# master branch configuration
-
  branches:
    only:
      - master

  skip_tags: true
  skip_commits:
    message: /Update.*\.md/

  version: 2.0.1.{build}
  configuration: Release
  os: Visual Studio 2015
  
  cache:
    - packages -> **\packages.config

  install:
    - SET PATH=%APPVEYOR_BUILD_FOLDER%\packages\PhantomJS.2.1.1\tools\phantomjs;%PATH%

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "2.0.1"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true

  environment:
    COVERALLS_REPO_TOKEN:
      secure: HujWqUkCgrw2hC1t45W2wPYqn8+/JC7VGJq/vawDBShdzZ3GxGpuQjj/ObK0665W
    GH_ACCESS_TOKEN:
      secure: r+IxpBcxWvxwGdiNvsHFEWa0wa8WPzw3uRi+1/ObwPoGS16bzG9FObtJIsFdmj0L

  before_build:
    - .nuget\nuget.exe restore .nuget\packages.config -PackagesDirectory packages
    - .nuget\nuget.exe restore Selenium.WebDriver.Extensions.sln

  build:
    project: Selenium.WebDriver.Extensions.sln

  after_build:
    - msbuild Selenium.WebDriver.Extensions.sln /property:Configuration=Release-Net45 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - msbuild Selenium.WebDriver.Extensions.sln /property:Configuration=Release-Net40 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - msbuild Selenium.WebDriver.Extensions.sln /property:Configuration=Release-Net35 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - msbuild Selenium.WebDriver.Extensions.sln /property:Configuration=Docs /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - nuget pack src\Selenium.WebDriver.Extensions\Selenium.WebDriver.Extensions.nuspec -Version 2.0.1

  test_script:
    - packages\xunit.runner.console.2.1.0\tools\xunit.console.exe test\Selenium.WebDriver.Extensions.Tests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all -appveyor
    - packages\xunit.runner.console.2.1.0\tools\xunit.console.exe test\Selenium.WebDriver.Extensions.IntegrationTests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.IntegrationTests.dll -noshadow -parallel all -appveyor -trait Browser=PhantomJS

  after_test:
    - packages\JetBrains.ReSharper.CommandLineTools.2016.1.20160414.162943\tools\inspectcode.exe Selenium.WebDriver.Extensions.sln --output=ReSharper.xml /no-swea
    - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:"packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:"test\Selenium.WebDriver.Extensions.Tests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all" -output:coverage.xml -filter:"+[Selenium.WebDriver.Extensions*]* -[*]*Exception* -[*Tests]* -[xunit*]*"
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml -f
    - packages\ReportGenerator.2.3.4.0\tools\ReportGenerator.exe -reports:coverage.xml -targetdir:CoverageReport
    - SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%"
    - pip install codecov
    - codecov -f coverage.xml

  artifacts:
    - path: ReSharper.xml
    - path: coverage.xml
    - path: docs\bin\Docs
    - path: CoverageReport
    - path: .\*.nupkg

  deploy:
    - provider: NuGet
      api_key:
        secure: kvwvA4clT64FDfanLoNcTLWpQlMGQ311zUfwAEljDwHhjtmFCy4O+gSZ2YrGTUYb
    - provider: GitHub
      release: 2.0.1
      artifact: /.*\.nupkg/
      auth_token:
        secure: r+IxpBcxWvxwGdiNvsHFEWa0wa8WPzw3uRi+1/ObwPoGS16bzG9FObtJIsFdmj0L

  on_success:
    - git clone -q -b gh-pages https://github.com/RaYell/selenium-webdriver-extensions.git docs\gh-pages
    - cd docs\gh-pages
    - git config --global credential.helper store
    - git config user.email "agent@appveyor.com"
    - git config user.name "AppVeyor Agent"
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GH_ACCESS_TOKEN):x-oauth-basic@github.com`n"
    - git rm -r api
    - xcopy ..\bin\Docs api /s /i
    - git add api
    - git commit -a -m "Documentation updated"
    - git push
    - cd ..\..

# develop, feature & bugfix branches
-
  branches:
    only:
      - develop
      - /feature.*/
      - /bugfix.*/

  skip_tags: true
  skip_commits:
    message: /Update.*\.md/

  version: 2.0.1.{build}
  configuration: Release
  os: Visual Studio 2015
  
  cache:
    - packages -> **\packages.config

  install:
    - SET PATH=%APPVEYOR_BUILD_FOLDER%\packages\PhantomJS.2.1.1\tools\phantomjs;%PATH%

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "2.0.1"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}-dev"

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true

  environment:
    COVERALLS_REPO_TOKEN:
      secure: HujWqUkCgrw2hC1t45W2wPYqn8+/JC7VGJq/vawDBShdzZ3GxGpuQjj/ObK0665W

  before_build:
    - .nuget\nuget.exe restore .nuget\packages.config -PackagesDirectory packages
    - .nuget\nuget.exe restore Selenium.WebDriver.Extensions.sln

  build:
    project: Selenium.WebDriver.Extensions.sln

  after_build:
    - msbuild Selenium.WebDriver.Extensions.sln /property:Configuration=Release-Net40 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - msbuild Selenium.WebDriver.Extensions.sln /property:Configuration=Release-Net45 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - msbuild Selenium.WebDriver.Extensions.sln /property:Configuration=Release-Net35 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - msbuild Selenium.WebDriver.Extensions.sln /property:Configuration=Docs /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - nuget pack src\Selenium.WebDriver.Extensions\Selenium.WebDriver.Extensions.nuspec -Version 2.0.1-dev

  test_script:
    - packages\xunit.runner.console.2.1.0\tools\xunit.console.exe test\Selenium.WebDriver.Extensions.Tests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all -appveyor
    - packages\xunit.runner.console.2.1.0\tools\xunit.console.exe test\Selenium.WebDriver.Extensions.IntegrationTests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.IntegrationTests.dll -noshadow -parallel all -appveyor -trait Browser=PhantomJS

  after_test:
    - packages\JetBrains.ReSharper.CommandLineTools.2016.1.20160414.162943\tools\inspectcode.exe Selenium.WebDriver.Extensions.sln --output=ReSharper.xml /no-swea
    - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:"packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:"test\Selenium.WebDriver.Extensions.Tests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all" -output:coverage.xml -filter:"+[Selenium.WebDriver.Extensions*]* -[*]*Exception* -[*Tests]* -[xunit*]*"
    - ps: If ($env:APPVEYOR_PULL_REQUEST_NUMBER -eq $null) { packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml -f }
    - packages\ReportGenerator.2.3.4.0\tools\ReportGenerator.exe -reports:coverage.xml -targetdir:CoverageReport
    - SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%"
    - pip install codecov
    - codecov -f coverage.xml

  artifacts:
    - path: ReSharper.xml
    - path: coverage.xml
    - path: docs\bin\Docs
    - path: CoverageReport
    - path: .\*.nupkg

# release branch configuration
-
  branches:
    only:
      - /release.*/

  skip_tags: true
  skip_commits:
    message: /Update.*\.md/

  version: 2.0.1.{build}
  configuration: Release
  os: Visual Studio 2015
  
  cache:
    - packages -> **\packages.config

  install:
    - SET PATH=%APPVEYOR_BUILD_FOLDER%\packages\PhantomJS.2.1.1\tools\phantomjs;%PATH%

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "2.0.1"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}-rc.2"

  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true

  environment:
    COVERALLS_REPO_TOKEN:
      secure: HujWqUkCgrw2hC1t45W2wPYqn8+/JC7VGJq/vawDBShdzZ3GxGpuQjj/ObK0665W

  before_build:
    - .nuget\nuget.exe restore .nuget\packages.config -PackagesDirectory packages
    - .nuget\nuget.exe restore Selenium.WebDriver.Extensions.sln

  build:
    project: Selenium.WebDriver.Extensions.sln

  after_build:
    - msbuild Selenium.WebDriver.Extensions.sln /property:Configuration=Release-Net45 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - msbuild Selenium.WebDriver.Extensions.sln /property:Configuration=Release-Net40 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - msbuild Selenium.WebDriver.Extensions.sln /property:Configuration=Release-Net35 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - msbuild Selenium.WebDriver.Extensions.sln /property:Configuration=Docs /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - nuget pack src\Selenium.WebDriver.Extensions\Selenium.WebDriver.Extensions.nuspec -Version 2.0.1-rc2

  test_script:
    - packages\xunit.runner.console.2.1.0\tools\xunit.console.exe test\Selenium.WebDriver.Extensions.Tests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all -appveyor
    - packages\xunit.runner.console.2.1.0\tools\xunit.console.exe test\Selenium.WebDriver.Extensions.IntegrationTests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.IntegrationTests.dll -noshadow -parallel all -appveyor -trait Browser=PhantomJS

  after_test:
    - packages\JetBrains.ReSharper.CommandLineTools.2016.1.20160414.162943\tools\inspectcode.exe Selenium.WebDriver.Extensions.sln --output=ReSharper.xml /no-swea
    - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:"packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:"test\Selenium.WebDriver.Extensions.Tests\bin\%CONFIGURATION%\Selenium.WebDriver.Extensions.Tests.dll -noshadow -parallel all" -output:coverage.xml -filter:"+[Selenium.WebDriver.Extensions*]* -[*]*Exception* -[*Tests]* -[xunit*]*"
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml -f
    - packages\ReportGenerator.2.3.4.0\tools\ReportGenerator.exe -reports:coverage.xml -targetdir:CoverageReport
    - SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%"
    - pip install codecov
    - codecov -f coverage.xml

  artifacts:
    - path: ReSharper.xml
    - path: coverage.xml
    - path: docs\bin\Docs
    - path: CoverageReport
    - path: .\*.nupkg

  deploy:
    - provider: NuGet
      api_key:
        secure: kvwvA4clT64FDfanLoNcTLWpQlMGQ311zUfwAEljDwHhjtmFCy4O+gSZ2YrGTUYb
    - provider: GitHub
      release: 2.0.1-rc.2
      artifact: /.*\.nupkg/
      auth_token:
        secure: r+IxpBcxWvxwGdiNvsHFEWa0wa8WPzw3uRi+1/ObwPoGS16bzG9FObtJIsFdmj0L
      prerelease: true
